blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.lerian.studio
    about: Check our documentation for guides and API reference
  - name: Discussions
    url: https://github.com/LerianStudio/midaz/discussions
    about: Ask questions and discuss with the community
