name: "PR Security Scan"

# This workflow runs security scans on pull requests
# targeting develop, release-candidate, and main branches

on:
  pull_request:
    branches:
      - develop
      - release-candidate
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  security-scan:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/pr-security-scan.yml@main
    with:
      runner_type: "firmino-lxc-runners"
      filter_paths: |-
        components/onboarding
        components/ledger
        components/console
      path_level: "2"
      dockerhub_org: "lerianstudio"
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}