name: Update Swagger On Git Pages

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  update-swagger-on-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_APP_ID }}
          private-key: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_PRIVATE_KEY }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY }}
          passphrase: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY_PASSWORD }}
          git_committer_name: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
          git_committer_email: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true


      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Get MIDAZ and Pages
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Running PWD: ===============================>"
          pwd 
          echo "Running LS: ================================>"
          ls
          
          echo "Cloning midaz: =============================>"
          gh repo clone LerianStudio/midaz
          
          echo "Cloning Page: ==============================>"          
          gh repo clone LerianStudio/LerianStudio.github.io
          
          echo "Running LS: ================================>"
          ls

      - name: Generate Swagger on Ledger and Transaction
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          cd midaz

          echo "Running SET ENV: ================================>"
          export PATH=$PATH:/usr/local/go/bin:$(go env GOPATH)/bin
          echo "Installing Swaggo: ================================>"
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "Swag installed at $(which swag): ================================>"
          swag --version
          echo "Go installed at $(which go): ================================>"
          
          make tidy
          
          make generate-docs-all  
          
          cd ..

      - name: Copy Swagger.json to Repo Ledger and Transaction
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Running PWD: ================================>"
          pwd 
          echo "Running LS: ================================>"
          ls
          
          cp midaz/components/ledger/api/swagger.json LerianStudio.github.io/ledger/ 

          cp midaz/components/transaction/api/swagger.json LerianStudio.github.io/transaction/

      - name: Commit and Push Swagger to Git Page
        run: |
          cd LerianStudio.github.io
          
          CURRENT_COMMIT=$(gh api repos/LerianStudio/LerianStudio.github.io/commits/main | jq -r .sha)

          gh api repos/LerianStudio/LerianStudio.github.io/commits/$CURRENT_COMMIT \
            -q '.files[].patch' > diff.patch

          # Check if the diff is empty
          if [ -s diff.patch ]; then
            echo "Changes detected in commit $CURRENT_COMMIT"
            cat diff.patch
          
            git add ledger
            git commit  -S -m "Update Swagger.json from Repo Ledger"
            
            git add transaction
            git commit  -S -m "Update Swagger.json from Repo Transaction"
            
            git push origin main
          
          else
            echo "No changes detected in commit $CURRENT_COMMIT"
          fi
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_AUTHOR_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}