name: Update Swagger On Git Pages

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  update-swagger-on-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_APP_ID }}
          private-key: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_PRIVATE_KEY }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY }}
          passphrase: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY_PASSWORD }}
          git_committer_name: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
          git_committer_email: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: midaz
          token: ${{ secrets.MANAGE_TOKEN }}

      - name: Generate Swagger on Ledger and Transaction
        working-directory: /home/runner/work/midaz/midaz
        run: |
          echo "Setting up Go environment"
          export PATH=$PATH:/usr/local/go/bin:$(go env GOPATH)/bin
          echo "Installing Swaggo"
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "Swag installed at $(which swag)"
          swag --version
          echo "Go installed at $(which go)"
          
          make tidy
          
          make generate-docs-all

      - name: Pull Git Pages
        uses: actions/checkout@v4
        with:
          repository: LerianStudio/LerianStudio.github.io
          ref: main
          path: page
          token: ${{ secrets.MANAGE_TOKEN }}

      - name: Copy Swagger.json to Repo Ledger and Transaction
        working-directory: /home/runner/work/midaz
        run: |
          pwd
          
          ls
        
          cp midaz/components/ledger/api/swagger.json page/ledger/ 

          cp midaz/components/transaction/api/swagger.json page/transaction/

      - name: Check Diff
        working-directory: /home/runner/work/midaz/page
        run: |
          git diff

      - name: Commit and Push Swagger to Git Page
        working-directory: /home/runner/work/midaz/page
        run: |
          git add page/ledger
          git commit  -S -m "Update Swagger.json from Repo Ledger"
          
          git add page/transaction
          git commit  -S -m "Update Swagger.json from Repo Transaction"
          
          git push origin main
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_AUTHOR_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
